# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: 
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Digital Skills Trainer | Freelance Writer & Tutor | Junior Data Analyst'
    twitter: ''
  analytics:
    google_analytics: 'G-PM0KBBJ8PR'
    google_tag_manager: 'GTM-MTRW299V' # Added Google Tag Manager
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    align: "right"
    show_search: true
    show_theme_chooser: true
    logo:
      text: "John Karanja"
      # Logo filename in `assets/media/` folder
      filename: ""
    # Shop a call-to-action button in the top right?
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© {year} John Karanja.' # This work is licensed under {license}'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
